name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via Clasp
        uses: erithion/clasp-action@main
        with:
          credentials: ${{ secrets.GAppScript_SA_CREDENTIALS }}
          scriptId: "1JNfOWh0Ai7cpGB3g4TWYQcg4wiK88NFjK9IMgajD22m9ODk3_w-n7Jus"
          rootDir: "."
