name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate with Google
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GAppScript_SA_CREDENTIALS }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Clasp
        run: npm install -g @google/clasp

      - name: Push Code
        run: clasp --adc push --force
